'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import {
  AlertTriangle,
  CheckCircle,
  XCircle,
  MessageCircle,
  Users,
  MapPin,
  DollarSign,
  TrendingUp,
  Download,
  Share2,
  HelpCircle,
  Loader2,
} from 'lucide-react'
import { toast } from 'sonner'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Progress } from '@/components/ui/progress'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Separator } from '@/components/ui/separator'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { getAnalysis, type AnalysisResult } from '@/lib/storage'

export default function AnalysisPage({ params }: { params: { id: string } }) {
  const router = useRouter()
  const [analysisData, setAnalysisData] = useState<AnalysisResult | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const data = getAnalysis(params.id)
    setAnalysisData(data)
    setLoading(false)
  }, [params.id])

  const getRiskColor = (score: number) => {
    if (score <= 35) return 'text-green-600'
    if (score <= 65) return 'text-yellow-600'
    return 'text-red-600'
  }

  const getRiskIcon = (category: AnalysisResult['riskCategory']) => {
    if (category === 'Low') return <CheckCircle className="h-5 w-5 text-green-600" />
    if (category === 'Medium') return <AlertTriangle className="h-5 w-5 text-yellow-600" />
    return <XCircle className="h-5 w-5 text-red-600" />
  }

  const getRecommendationClass = (recommendation: AnalysisResult['recommendation']) => {
    if (recommendation === 'Approve') return 'bg-green-50 text-green-700 border-green-200'
    if (recommendation === 'Review') return 'bg-yellow-50 text-yellow-700 border-yellow-200'
    return 'bg-red-50 text-red-700 border-red-200'
  }

  const getConfidenceBadge = (confidence?: AnalysisResult['confidence']) => {
    switch (confidence) {
      case 'High':
        return <Badge className="bg-green-100 text-green-700 border-green-200">High Confidence</Badge>
      case 'Medium':
        return <Badge className="bg-yellow-100 text-yellow-700 border-yellow-200">Medium Confidence</Badge>
      case 'Low':
        return (
          <Badge className="bg-orange-100 text-orange-700 border-orange-200">
            Low Confidence - limited data
          </Badge>
        )
      default:
        return null
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-50">
        <div className="text-center">
          <Loader2 className="mx-auto mb-4 h-10 w-10 animate-spin text-blue-600" />
          <p className="text-gray-600">Loading analysis...</p>
        </div>
      </div>
    )
  }

  if (!analysisData) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-50 px-4">
        <Card className="w-full max-w-md p-8 text-center shadow-sm transition-shadow hover:shadow-md">
          <XCircle className="mx-auto mb-4 h-12 w-12 text-red-500" />
          <h2 className="mb-2 text-xl font-semibold text-gray-900">Analysis not found</h2>
          <p className="mb-6 text-sm text-gray-600">
            This analysis may have been cleared from local storage.
          </p>
          <Button asChild>
            <Link href="/">Go to Homepage</Link>
          </Button>
        </Card>
      </div>
    )
  }

  const downloadReport = () => {
    const content = `
VERDEX - LOAN ANALYSIS REPORT
==============================
Date: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}
Applicant: ${analysisData.applicantName}

RISK ASSESSMENT
---------------
Risk Score: ${analysisData.riskScore}/100 (${analysisData.riskCategory} Risk)
Recommendation: ${analysisData.recommendation}
Confidence: ${analysisData.confidence ?? 'N/A'}

KEY FACTORS
-----------
${analysisData.keyFactors.map((factor) => `• ${factor}`).join('\n')}

EXPLANATION
-----------
${analysisData.explanation}

BIAS ASSESSMENT
---------------
Gender Bias Risk:   ${analysisData.biasFactors.gender}%
Location Bias Risk: ${analysisData.biasFactors.location}%
Income Bias Risk:   ${analysisData.biasFactors.income}%
Age Bias Risk:      ${analysisData.biasFactors.age}%
Overall Bias Risk:  ${analysisData.biasFactors.overall}%

==============================
Generated by Verdex - verdex.vercel.app
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = `verdex-report-${params.id}.txt`
    anchor.click()
    URL.revokeObjectURL(url)
  }

  const shareAnalysis = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href)
      toast.success('Link copied to clipboard!')
    } catch {
      toast.error('Unable to copy link right now.')
    }
  }

  return (
    <TooltipProvider>
      <div className="min-h-screen bg-gray-50 p-4">
        <div className="mx-auto max-w-6xl">
          <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
            <div>
              <h1 className="text-3xl font-bold tracking-tight text-gray-900">Loan Analysis Results</h1>
              <p className="text-sm text-gray-600">Analysis ID: {params.id}</p>
            </div>
            <div className="flex flex-wrap gap-2">
              <Button variant="outline" className="gap-2" onClick={downloadReport}>
                <Download className="h-4 w-4" />
                Download Report
              </Button>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button variant="outline" className="gap-2" onClick={shareAnalysis}>
                    <Share2 className="h-4 w-4" />
                    Share
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Link works on this device only</TooltipContent>
              </Tooltip>
              <Button className="gap-2" onClick={() => router.push(`/chatbot?id=${params.id}`)}>
                <MessageCircle className="h-4 w-4" />
                Chat with AI
              </Button>
            </div>
          </div>

          <Separator className="mb-6" />

          <Tabs defaultValue="overview" className="space-y-6">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="overview">Overview</TabsTrigger>
              <TabsTrigger value="bias">Bias Analysis</TabsTrigger>
              <TabsTrigger value="factors">Key Factors</TabsTrigger>
            </TabsList>

            <TabsContent value="overview" className="space-y-6">
              <Card className="shadow-sm transition-shadow hover:shadow-md">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    {getRiskIcon(analysisData.riskCategory)}
                    Risk Score
                    <Dialog>
                      <DialogTrigger asChild>
                        <Button variant="ghost" size="icon" className="h-7 w-7">
                          <HelpCircle className="h-4 w-4 text-gray-500" />
                        </Button>
                      </DialogTrigger>
                      <DialogContent>
                        <DialogHeader>
                          <DialogTitle>Risk Score Guide</DialogTitle>
                        </DialogHeader>
                        <pre className="whitespace-pre-wrap text-sm text-gray-700">
{`Risk Score Guide
────────────────
0–35   Low Risk     → Strong application. Likely to be approved.
36–65  Medium Risk  → Mixed signals. Manual review recommended.
66–100 High Risk    → Significant concerns. High chance of decline.

Bias Score Guide
────────────────
0–20   Low     → Minimal demographic influence detected
21–40  Medium  → Some factors may need review
41–100 High    → Potential bias detected — human review advised

Note: Verdex scores are AI-generated estimates, not official credit decisions.`}
                        </pre>
                      </DialogContent>
                    </Dialog>
                  </CardTitle>
                  <CardDescription>Applicant: {analysisData.applicantName}</CardDescription>
                </CardHeader>
                <CardContent className="grid gap-6 md:grid-cols-3">
                  <div className="text-center">
                    <p className={`text-6xl font-black ${getRiskColor(analysisData.riskScore)}`}>
                      {analysisData.riskScore}
                    </p>
                    <p className="mt-1 text-sm text-gray-600">out of 100</p>
                    <Progress value={analysisData.riskScore} className="mt-3" />
                  </div>
                  <div className="space-y-3 text-center">
                    <Badge className="px-4 py-2 text-base">{analysisData.riskCategory} Risk</Badge>
                    <p className="text-sm text-gray-600">Risk Category</p>
                    {getConfidenceBadge(analysisData.confidence)}
                  </div>
                  <div className="space-y-3 text-center">
                    <Badge
                      variant="outline"
                      className={`border px-4 py-2 text-base ${getRecommendationClass(analysisData.recommendation)}`}
                    >
                      {analysisData.recommendation}
                    </Badge>
                    <p className="text-sm text-gray-600">Recommendation</p>
                  </div>
                </CardContent>
              </Card>

              <Card className="shadow-sm transition-shadow hover:shadow-md">
                <CardHeader>
                  <CardTitle>Verdex Explanation</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="leading-relaxed text-gray-700">{analysisData.explanation}</p>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="bias" className="space-y-6">
              <Card className="shadow-sm transition-shadow hover:shadow-md">
                <CardHeader>
                  <CardTitle>Bias Analysis</CardTitle>
                  <CardDescription>Bias risk across major demographic dimensions.</CardDescription>
                </CardHeader>
                <CardContent className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-4">
                    <div className="flex items-center gap-3">
                      <Users className="h-4 w-4 text-blue-600" />
                      <div className="w-full">
                        <div className="mb-1 flex justify-between text-sm">
                          <span>Gender</span>
                          <span>{analysisData.biasFactors.gender}%</span>
                        </div>
                        <Progress value={analysisData.biasFactors.gender} />
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <MapPin className="h-4 w-4 text-green-600" />
                      <div className="w-full">
                        <div className="mb-1 flex justify-between text-sm">
                          <span>Location</span>
                          <span>{analysisData.biasFactors.location}%</span>
                        </div>
                        <Progress value={analysisData.biasFactors.location} />
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <DollarSign className="h-4 w-4 text-yellow-600" />
                      <div className="w-full">
                        <div className="mb-1 flex justify-between text-sm">
                          <span>Income</span>
                          <span>{analysisData.biasFactors.income}%</span>
                        </div>
                        <Progress value={analysisData.biasFactors.income} />
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <TrendingUp className="h-4 w-4 text-purple-600" />
                      <div className="w-full">
                        <div className="mb-1 flex justify-between text-sm">
                          <span>Age</span>
                          <span>{analysisData.biasFactors.age}%</span>
                        </div>
                        <Progress value={analysisData.biasFactors.age} />
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center justify-center">
                    <div className="text-center">
                      <p className="text-5xl font-black text-blue-700">{analysisData.biasFactors.overall}%</p>
                      <p className="mt-2 text-sm text-gray-600">Overall Bias Risk</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="factors">
              <Card className="shadow-sm transition-shadow hover:shadow-md">
                <CardHeader>
                  <CardTitle>Key Factors</CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-3">
                    {analysisData.keyFactors.map((factor, index) => (
                      <li key={`${factor}-${index}`} className="flex items-start gap-2 text-gray-700">
                        <CheckCircle className="mt-0.5 h-4 w-4 text-green-600" />
                        <span>{factor}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </TooltipProvider>
  )
}
